INSERT INTO TECHNOLOGIES(name, version) VALUES ('Java','15');
INSERT INTO TECHNOLOGIES(name, version) VALUES ('Python','3.9.2');
INSERT INTO TECHNOLOGIES(name, version) VALUES ('Maven','4.0.0');
INSERT INTO TECHNOLOGIES(name, version) VALUES ('Hibernate','5.4.0 final');
INSERT INTO TECHNOLOGIES(name, version) VALUES ('Spring','2.4.2');

INSERT INTO CANDIDATES(FIRST_NAME, LAST_NAME, TYPE, DOCUMENT, DATE_OF_BIRTH) VALUES ( 'Noob','Saibot', 'DNI', '800.000','1920-01-01');
INSERT INTO CANDIDATES(FIRST_NAME, LAST_NAME, TYPE, DOCUMENT, DATE_OF_BIRTH) VALUES ( 'Mario','Bros', 'DNI', '25.000.000','1983-03-02');
INSERT INTO CANDIDATES(FIRST_NAME, LAST_NAME, TYPE, DOCUMENT, DATE_OF_BIRTH) VALUES ( 'Samus','Aran', 'DNI', '30.000.000','1986-02-03');

INSERT INTO TECHNOLOGIES_BY_CANDIDATE(exp, id_tecnology, id_candidate) values ( 5,1,1 );
INSERT INTO TECHNOLOGIES_BY_CANDIDATE(exp, id_tecnology, id_candidate) values ( 5,3,1 );
INSERT INTO TECHNOLOGIES_BY_CANDIDATE(exp, id_tecnology, id_candidate) values ( 5,5,1 );

